apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-charge
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app.kubernetes.io/name: service-charge
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app.kubernetes.io/name: service-charge
    spec:
      containers:
      - name: service-charge
        image: nitinsingh01/service-charge
        ports:
        - containerPort: 8080
        env:
            - name: MONGO_URI
              value: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: service-charge
  labels:
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-charge